import React, { useState, useEffect, useMemo } from 'react';
import axios from 'axios';

// Assume shadcn/ui components are available.
// If not, these would need to be created by `npx shadcn@latest add <component>`
// For this subtask, we'll assume they exist and can be imported.
// If running locally, ensure these are correctly installed and generated by shadcn CLI.

// Placeholder imports for shadcn/ui components.
// In a real shadcn setup, these would point to '@components/ui/...'
const Table = ({ children, ...props }) => <table {...props}>{children}</table>;
const TableHeader = ({ children, ...props }) => <thead {...props}>{children}</thead>;
const TableBody = ({ children, ...props }) => <tbody {...props}>{children}</tbody>;
const TableRow = ({ children, ...props }) => <tr {...props}>{children}</tr>;
const TableHead = ({ children, ...props }) => <th {...props}>{children}</th>;
const TableCell = ({ children, ...props }) => <td {...props}>{children}</td>;
const Button = ({ children, ...props }) => <button {...props}>{children}</button>;
const Select = ({ children, value, onChange, ...props }) => <select value={value} onChange={onChange} {...props}>{children}</select>;
const SelectTrigger = ({ children, ...props }) => <div>{children}</div>; // Simplified placeholder
const SelectContent = ({ children, ...props }) => <div>{children}</div>; // Simplified placeholder
const SelectItem = ({ children, value, ...props }) => <option value={value} {...props}>{children}</option>; // Simplified placeholder
const Input = (props) => <input {...props} />;
const DropdownMenu = ({ children, ...props }) => <div {...props}>{children}</div>; // Simplified placeholder
const DropdownMenuTrigger = ({ children, ...props }) => <div {...props}>{children}</div>; // Simplified placeholder
const DropdownMenuContent = ({ children, ...props }) => <div {...props}>{children}</div>; // Simplified placeholder
const DropdownMenuItem = ({ children, ...props }) => <div {...props}>{children}</div>; // Simplified placeholder


const API_URL = '/api/user/games';
// Placeholder JWT. In a real app, this would come from auth context or localStorage.
const PLACEHOLDER_TOKEN = 'VALID_TOKEN_FOR_TESTING';

// Mock game data structure (adjust based on actual API response)
const mockGameData = [
  {
    game_rawg_id: 3498,
    name: "The Witcher 3: Wild Hunt",
    background_image: "https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg",
    status: "Completed",
    rating: 5,
    review_text: "Amazing game!",
    added_at: "2023-01-15T10:00:00Z",
    updated_at: "2023-01-20T12:00:00Z"
  },
  {
    game_rawg_id: 5286,
    name: "Red Dead Redemption 2",
    background_image: "https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg",
    status: "Playing",
    rating: null,
    review_text: "",
    added_at: "2023-02-20T15:30:00Z",
    updated_at: "2023-03-10T18:45:00Z"
  },
  {
    game_rawg_id: 4200,
    name: "Portal 2",
    background_image: "https://media.rawg.io/media/games/328/3283617cb7d75d67257fc58339188742.jpg",
    status: "Want to Play",
    rating: null,
    review_text: "",
    added_at: "2023-03-01T11:20:00Z",
    updated_at: "2023-03-01T11:20:00Z"
  }
];

const gameStatuses = ["All", "Playing", "Completed", "Want to Play", "Dropped", "Paused", "Wishlist"];

function MyCollectionPage() {
  const [games, setGames] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [statusFilter, setStatusFilter] = useState('All');
  const [sortConfig, setSortConfig] = useState({ key: 'name', direction: 'ascending' });

  useEffect(() => {
    const fetchGames = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const response = await axios.get(API_URL, {
          headers: {
            'Authorization': `Bearer ${PLACEHOLDER_TOKEN}`
          }
        });
        // Assuming the backend for /api/user/games returns data similar to mockGameData
        // If it returns the simpler structure from user_games, we'd need to adjust
        // or make additional calls to get full game details (name, image).
        // For this subtask, we'll assume the API returns enriched data.
        setGames(response.data.length > 0 ? response.data : mockGameData); // Use mock if empty for UI dev
      } catch (err) {
        console.error("Error fetching game collection:", err);
        setError(err.response?.data?.message || err.message || 'Failed to fetch game collection.');
        setGames(mockGameData); // Load mock data on error to continue UI development
      } finally {
        setIsLoading(false);
      }
    };

    fetchGames();
  }, []);

  const sortedAndFilteredGames = useMemo(() => {
    let filtered = games;
    if (statusFilter !== 'All') {
      filtered = games.filter(game => game.status === statusFilter);
    }

    return [...filtered].sort((a, b) => {
      if (a[sortConfig.key] < b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? -1 : 1;
      }
      if (a[sortConfig.key] > b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? 1 : -1;
      }
      return 0;
    });
  }, [games, statusFilter, sortConfig]);

  const requestSort = (key) => {
    let direction = 'ascending';
    if (sortConfig.key === key && sortConfig.direction === 'ascending') {
      direction = 'descending';
    }
    setSortConfig({ key, direction });
  };

  if (isLoading) return <p>Loading your game collection...</p>;
  if (error) return <p style={{ color: 'red' }}>Error: {error}</p>;

  return (
    <div style={{ padding: '20px' }}>
      <h1>My Game Collection</h1>
      
      <div style={{ marginBottom: '20px', display: 'flex', gap: '10px' }}>
        <Select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
          {/* <SelectTrigger><Button>Filter by Status: {statusFilter}</Button></SelectTrigger> */}
          {/* <SelectContent> */}
            {gameStatuses.map(status => (
              <SelectItem key={status} value={status}>{status}</SelectItem>
            ))}
          {/* </SelectContent> */}
        </Select>
        {/* Simple sort buttons for now. Ideally, these are part of the table headers. */}
        <Button onClick={() => requestSort('name')}>Sort by Name {sortConfig.key === 'name' ? (sortConfig.direction === 'ascending' ? '▲' : '▼') : ''}</Button>
        <Button onClick={() => requestSort('status')}>Sort by Status {sortConfig.key === 'status' ? (sortConfig.direction === 'ascending' ? '▲' : '▼') : ''}</Button>
        <Button onClick={() => requestSort('rating')}>Sort by Rating {sortConfig.key === 'rating' ? (sortConfig.direction === 'ascending' ? '▲' : '▼') : ''}</Button>
      </div>

      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Cover</TableHead>
            <TableHead onClick={() => requestSort('name')}>Name {sortConfig.key === 'name' ? (sortConfig.direction === 'ascending' ? '▲' : '▼') : ''}</TableHead>
            <TableHead onClick={() => requestSort('status')}>Status {sortConfig.key === 'status' ? (sortConfig.direction === 'ascending' ? '▲' : '▼') : ''}</TableHead>
            <TableHead onClick={() => requestSort('rating')}>Your Rating {sortConfig.key === 'rating' ? (sortConfig.direction === 'ascending' ? '▲' : '▼') : ''}</TableHead>
            <TableHead>Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {sortedAndFilteredGames.map((game) => (
            <TableRow key={game.game_rawg_id}>
              <TableCell>
                {game.background_image ? (
                  <img src={game.background_image} alt={game.name || 'Game cover'} style={{ width: '50px', height: 'auto', borderRadius: '4px' }} />
                ) : (
                  'No image'
                )}
              </TableCell>
              <TableCell>{game.name || `Game ID: ${game.game_rawg_id}`}</TableCell>
              <TableCell>{game.status}</TableCell>
              <TableCell>{game.rating ? `${game.rating}/5` : 'Not rated'}</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger><Button variant="outline">Actions</Button></DropdownMenuTrigger>
                  <DropdownMenuContent>
                    <DropdownMenuItem>Change Status</DropdownMenuItem>
                    <DropdownMenuItem>Write/Edit Review</DropdownMenuItem>
                    <DropdownMenuItem>View Logs</DropdownMenuItem>
                    <DropdownMenuItem>View Game Details</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      {sortedAndFilteredGames.length === 0 && <p>No games match your filters, or your collection is empty.</p>}
    </div>
  );
}

export default MyCollectionPage;

// Basic CSS for table sorting indicators (optional, Tailwind would handle this better)
// Add to your globals.css or component's style if not using a UI library that handles this
const styles = `
  th {
    cursor: pointer;
    user-select: none;
  }
  th:hover {
    background-color: #f0f0f0;
  }
`;
// You can inject this with a <style> tag in the component for simplicity if needed,
// but external CSS or Tailwind is preferred.
// e.g. <style>{styles}</style> at the top level of the component return.
// For now, this is just a comment.
